# .deepsource.toml
# Configuración de DeepSource para mi-app-segura
 
version = 1   # Versión del esquema de DeepSource
 
# 1. Rutas que no queremos que se analicen (dependencias, builds, imágenes…)
skip_paths = [
  "node_modules/",
  "dist/",
  "build/",
  "docs/images/"
]
 
# 2. Ajustes globales de problemas
#    Solo queremos ver problemas de nivel “major” o más grave.
minimum_severity = "major"
 
[issues]
# No necesitamos analizar los tests automáticos ni la documentación
exclude = [
  "tests/**/*.js",
  "docs/**/*.md"
]
 
# 3. Analizadores
#    DeepSource unifica ESLint, detección de vulnerabilidades y demás
#    en un único analyzer “javascript”.
 
[[analyzers]]
name    = "javascript"
enabled = true
 
[analyzers.javascript]
# Le indicamos que usamos Node.js v18+ y que también tenemos entorno de browser y Jest
runtime_version = ">=18"
environment     = ["nodejs", "browser", "jest"]
 
# 4. Formatter automático
#    Utilizamos Prettier para formatear el código en cada push/Push request
 
[[transformers]]
name    = "prettier"
enabled = true
 
# 5. Integración en el flujo de Git
[reporter]
# Aparecerá un status check “DeepSource/analysis” en cada commit y Push request
reports = ["commit", "pull_request"]